services:
    subscriber.click:
        class: ClickBundle\EventSubscriber\ClickSubscriber
        arguments:
            - "@repository.click"
        tags:
            - { name: kernel.event_subscriber }